### ISSUE TITLE
¿Qué hacer con branches ya mergeados?

### ISSUE THREAD

**Issue by elbaby** [Mikroways/wfc-afip-sandbox#11]
@chrodriguez,

como no sé cuál es la forma "oficial" de preguntarte algo (y para no esperar hasta el miércoles ni joderte por mail) lo hago acá.

Yo soy un viejo que "se quedó en el '45". Usé cvs y svn (y lo sigo usando para mis documentos personales) pero para cuando empecé a usar git ya no desarrollaba nada ni mantenía configuraciones operativas seriamente, con lo cual vivo gugliando en stackoverflow para ver cómo se hacen las cosas con git (o usando machetes como [este](https://www.git-tower.com/blog/git-for-subversion-users-cheat-sheet/))

Con esto, estoy aprovechando el curso para acostumbrarme a usar branches y esas cosas _modernas_ :smile:

La pregunta es, ¿cuál es la 'mejor práctica' respecto de branches que ya se mergearon? Yo tendería a borrarlos, dado que la historia del brach igual queda en el repositorio y que, al menos a mí (o a mi TOC) me molesta que aparezcan todos los branches viejos cuando los listo (o cuando tiro `git checkout <tab><tab>`).

**Comment by chrodriguez** [comment]
Buenas @elbaby! Mirá la idea es eliminarlas si. De hecho, si resolver localmente todo en tu máquina local, no subis la rama al remote. 

Incluso estas herramientas (lo digo por github y por gitlab), al hacer el MR o PR te preguntan como hacer el merge:

![Screenshot_20201016-182349](https://user-images.githubusercontent.com/1460882/96310000-ce1a8b80-0fdc-11eb-9e16-3740e42e0e46.png)

Lo que no se usa molesta. Borralos porque quedan en el master con la historia de commits según el caso elegido

Abrazo

**Comment by elbaby** [comment]
Excelente. Muchas gracias.
