### ISSUE TITLE
convención para el nombre de archivo

### ISSUE THREAD

**Issue by afreisinger** [Mikroways/wfc-afip-sandbox#2]
Siguiendo la convención para el nombre de archivo: alumno-{apellido}.{nombre}/README.md
Verificar ./afip/docente-rodriguez-christian
Corrección ./afip/docente-rodriguez.christian

**Comment by chrodriguez** [comment]
Muy bien verificando el enunciado. Y yo le pifié porque se me recontra pasó. ¡Gracias por el aporte! Ahora veo que tu carpeta tampoco lo respeta, pero se que fui yo el que hizo ruido, jaja

**Comment by chrodriguez** [comment]
Acomodé la carpeta tuya para no confundir al resto. ¡Gracias!
